export const GAME_STATUS_START = 'GAME_STATUS_START';
export const GAME_STATUS_ONGOING = 'GAME_STATUS_ONGOING';
export const GAME_STATUS_ENDED = 'GAME_STATUS_END';

export const MAX_GRAPH_CHANGES_TO_SHOW = 20;
export const LEVEL_UPGRADE_EVERY_TOT_CHANGES = 20;
export const WHALES_ENABLED_EVERY_TOT_SECONDS = 15;
export const WHALES_CHANGES_DURATION = 7;
export const FINAL_LEVEL = 10;
export const FUNDS_MAX_DECIMALS = 3;
export const TRUNC_FOR_MAX_DECIMALS = Math.pow(10, FUNDS_MAX_DECIMALS);
